function [template] = define_template(...
    MaxNumSplits, Surrogate, MinLeafSize,...
    PredictorSelection, SplitCriterion, PruneCriterion, NPredictorsToSample)

% Function to define a decision tree template.
% Inputs:
%   MaxNumSplits: maximum number of decision splits.
%   MinLeafSize: minimum observations per leaf.
%   MinParentSize: minimum observations per branch node.
% Outputs:
%   template: decision tree template.

% Define decision tree template
template = templateTree(...
    'numpredictorstosample', NPredictorsToSample,...
    'predictorselection', PredictorSelection,...
    'surrogate', Surrogate,...
    'maxnumsplits', MaxNumSplits,...
    'minleafsize', MinLeafSize,...
    'reproducible', true,...
    'splitcriterion', SplitCriterion,...
    'mergeleaves', 'on',...
    'prune', 'on', 'prunecriterion', PruneCriterion);

end